### ISSUE TITLE
无法正常调用

### ISSUE THREAD

**Issue by HMScygnet** [noisky/Random-Image-Api#3]
进入localhost:9090/random后显示此图片，list是正常加载的![image](https://img.ffis.me/images/2020/01/08/QQ20200108160257.png)

**Comment by noisky** [comment]
调用地址为文件名去除后缀；
例如图片名为：acg.txt
程序提示地址加载完毕后
对应的调用地址为：localhost:9090/random/acg

**Comment by HMScygnet** [comment]
使用正确地址后仍然无法正常调用，这是后台与效果图
![1](https://user-images.githubusercontent.com/65561426/135473792-db03c3a9-fef2-43b7-8d12-975f386199f2.png)
![2](https://user-images.githubusercontent.com/65561426/135473853-7dddf63c-9e00-4e01-bdf5-ee55496b1e9e.png)

**Comment by noisky** [comment]
浏览器直接访问为空referer请求，程序默认禁止了空referer请求，将其跳转为首页；
如需开启，则修改配置文件为：
```
server:
  port: 9090 # 服务端口
# 自定义设置
customize:
  noReferer: true # 是否允许referer为空
```
